name = "gleam_zlists"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "A library for working with lazy lists in Gleam"

[docs]
links = [
  { title = 'GitHub', href = 'https://github.com/mrdimosthenis/gleam_zlists' }
]

[repository]
type = "github"
user = "mrdimosthenis"
repo = "gleam_zlists"

[dependencies]
gleam_stdlib = "~> 0.40.0"
zlists = "~> 0.0.4"

[dev-dependencies]
gleeunit = "~> 1.2.0"
